### ISSUE TITLE
[Maps] Instancier une map

### ISSUE THREAD

**Issue by Urthawen** [hussein-aitlahcen/codebreak#12]
Avoir la possibilité d'instancier une map

**Comment by hussein-aitlahcen** [comment]
@Urthawen Explique, parce que pour le moment les maps multi instances existes (une map par joueur)

**Comment by Urthawen** [comment]
@hussein-aitlahcen Ah d'accord, c'est ce que je voulais. Tu le définies où ?

**Comment by hussein-aitlahcen** [comment]
@Urthawen Il me semble que c'est en dur dans le code, c'est une liste de maps dans le fichier [WorldConfig](https://github.com/hussein-aitlahcen/codebreak/blob/master/src/Codebreak.Service.World/WorldConfig.cs#L208).

Je devais déplacer cette option dans la base, mais pas encore fait.

**Comment by Urthawen** [comment]
@hussein-aitlahcen Ok j'irais look. Merci
