### ISSUE TITLE
[Quêtes] - Quête fantôme ? + Objectifs incorrect

### ISSUE THREAD

**Issue by Urthawen** [hussein-aitlahcen/codebreak#3]
- Lorsque le joueur possède une ou plusieurs quêtes, une quête "fantôme" s'ajoute automatiquement : 
  <img>http://puu.sh/qSu5H/e542aa0489.jpg</img> (Image IG)
  http://puu.sh/qSu83/f13b398262.png (Image console - World lorsque je clique sur cette quête)<br/>
- Des objectifs s'ajoutent sur les autres quêtes (Sur cet exemple, je possède deux fois l'objectif "Vaincre x1 Chafer d'Elite en un seul combat", alors qu'elle est supposée être seulement dans la quête "Jusqu'au bout du Monde")
  http://puu.sh/qSugE/7fe8a712a5.jpg (Image IG)

**Comment by hussein-aitlahcen** [comment]
@Urthawen Normalement le premier point devrait être fixé, peut être qu'il corrigera automatiquement le second, vérifie et valide moi ça s'il te plait

**Comment by Urthawen** [comment]
@hussein-aitlahcen Premier point fixé, le deuxième est toujours d'actualité

**Comment by hussein-aitlahcen** [comment]
@Urthawen vérifie de nouveau avec ce dernier commit s'il te plait.
